#!/usr/bin/env python3
"""Turn your private list of blocked terms into the hash list the guard uses.

    tools/guard/make_hashes.py .guard/terms.local.txt

Input: one term per line (a word or a phrase; '#' starts a comment). The input
file stays on your machine: .guard/ is ignored by git. Output is
tools/guard/blocked_terms.sha256, which is safe to commit: it contains only
SHA-256 hashes of the normalised terms.

A hash list hides the words from a casual reader and from search engines. It
is not encryption: anyone can test a guess against it. Do not put secrets in it.
"""
import hashlib
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent / "blocked_terms.sha256"


def normalise(term: str) -> str:
    return " ".join(re.findall(r"[a-z0-9]+", term.lower()))


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    terms = set()
    for line in Path(sys.argv[1]).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line and normalise(line):
            terms.add(normalise(line))
            terms.add(normalise(line).replace(" ", ""))      # "some name" also as "somename"
    singles = sorted({len(t) for t in terms if " " not in t and len(t) >= 5})
    lines = ["# SHA-256 of blocked terms (lowercase words joined by single spaces). Generated by make_hashes.py.",
             "# embedded-lengths: " + ",".join(map(str, singles))]
    lines += sorted(hashlib.sha256(t.encode()).hexdigest() for t in terms)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(terms)} hashes to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
