// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    { type: 'category', label: 'Getting started', collapsed: false, items: ['getting-started/install', 'getting-started/configure'] },
    {
      type: 'category', label: 'Guides', collapsed: false,
      items: ['guides/recorded-lectures', 'guides/live-classes', 'guides/build-and-review', 'guides/evaluation', 'guides/study-method'],
    },
    { type: 'category', label: 'Concepts', items: ['concepts/architecture', 'concepts/privacy'] },
    { type: 'category', label: 'Reference', items: ['reference/cli', 'reference/configuration', 'reference/troubleshooting'] },
    {
      type: 'category', label: 'Project',
      items: ['project/roadmap', 'project/design-review', 'project/tech-debt', 'project/testing', 'project/content-guard', 'project/licensing-and-names'],
    },
    { type: 'category', label: 'Decisions', items: [{ type: 'autogenerated', dirName: 'decisions' }] },
  ],
};
module.exports = sidebars;
